### ISSUE TITLE
Unit tests for @cuba-platform/cuba-react-ui are not run at CI

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#106]
Travis uses `npm run lerna run coverage` which won't launch tests from `@cuba-platform/cuba-react-ui` as there is no `coverage` script there.

**Comment by vadimbasko** [comment]
I think we should not mix test(unit) and coverage tasks. I suggest to add two separate scripts in each package (test:unit and coverage) and use it by call
`lerna run test:unit` and `lerna run coverage`

**Comment by vadimbasko** [comment]
Also, we need to define and separate our test types (unit, component, integration, e2e). At this moment I don't fully understand which tests is related to which type. As example - it's not correct to name cuba-rest services 'unit', because we need to run scr backend for it.
