### ISSUE TITLE
DataTable: No error message when filtering results in a failed request

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#108]
### QA Notes

Can be tested with setting network to offline in dev tools. Filtering, sorting the table, paginating, etc. should now result in an error message.

**Comment by IskandarovRost** [comment]
Closed
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/66be555f-67a1-4b81-b6e3-34485bdf3b7a)
