### ISSUE TITLE
Russian locale is enabled in React client when it was not added to project

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#117]
1) Using Studio create a brand-new project 
2) Do not add Russian locale - leave only the English one
![image](https://user-images.githubusercontent.com/19840141/74339483-9ad48c80-4dbd-11ea-9cd0-2be16ff88601.png)
3) Create *React* front module
4) Start the appliction, wait all the processes completion
5) Open front-end URL
**AR:** Russian is available

![image](https://user-images.githubusercontent.com/19840141/74340750-f30c8e00-4dbf-11ea-8e5a-cc2b5aefeb3c.png)

# QA Notes

Frontend client saves the chosen locale in local storage under `{app name}_cubaLocale` key. You may want to clear it during testing. Otherwise you may encounter situation when the client picks up a locale that you have removed from the project.

**Comment by vyacheslav-pushkin** [comment]
Blocked by STUDIO-8363
