### ISSUE TITLE
Ability to simply generate front-end components for new entities, added after 'front' module was created

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#143]
Using Studio:

1) Create a project
2) Create some entity ("NewEntity")
3) Create React 'front' module (Using "CUBA->Advanced->Manage Modules" menu item in Studio)
4) For the entity, create Front Component
It works OK
5) Create another entity ("NewEntity_2")
6) Create Front Component for it - Entity management
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/ffa172ca-05e1-4f8a-aca6-d4a2b9d7d9f4)
7) Assemble/restart the project

**AR:** build fails as the new entity is not presented in 'cuba/entities'. 
User should manually create it or re-create the 'front' module after adding an entity.
```
> simplfe@0.1.0 build D:\projects\2020.02.28\simplfe\modules\front
> react-scripts build

Creating an optimized production build...
Failed to compile.

.\src\app\newentity_2\NewEntity_2List.tsx
Cannot find module: '../../cuba/entities/simplfe_NewEntity_2'. Make sure this package is installed.

You can install this package by running: npm install ../../cuba/entities/simplfe_NewEntity_2.
```

**ER:** It seems, if the entity is missed in 'front'-client, it should be added to the project model when creating a component,
If some Studio changes required, please create the ticket in YouTrack.

**Comment by skatova** [comment]
Issue fixed
[https://youtrack.haulmont.com/issue/STUDIO-8553](url)
