### ISSUE TITLE
Editor behavior when backend cannot be reached

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#154]
**Steps to reproduce**

1. Open an entity browser
2. Shutdown backend
3. Attempt to edit an entity

**Expected behavior**

Error message stating that an attempt to load an entity has failed

**Actual behavior**

No error messages, empty editor opens. Attempting to submit the form results in no reaction.

**Comment by maistrenkoIulia** [comment]
**Reopened**
v. 4.0.0-beta.1
for edit entity - ok
for create new entity - NOK
TC: run app>open front
set network>offline
open entity management>create
ER: error should be displayed
AR: form for creation displayes, user sets data>Submit> 'Error'

![image](https://user-images.githubusercontent.com/66992566/105357602-7bb9be00-5c0e-11eb-9897-ea8d1ccb2884.png)
