### ISSUE TITLE
Need to manualy run 'npm install' after react-typescript frontend is created

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#189]
-Environment
CUBA Platform version: 7.2.4
CUBA Studio plugin version: 13.2-191
IntelliJ version: IntelliJ IDEA 2020.1 (Ultimate Edition)
Linux Ubuntu 19.10
Node 12.16.1, npm 6.13.4
Frontend generator 3.0.0-beta.0

The same is for Studio and CLI
1) In some project create fronend-module
2) Specifying 3.0.0-beta.0
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/564ba3d5-12d0-405c-8c3b-c2f91fd67dad)
3) start the project

**AR:** Could not find package-lock.json. Running "npm install" in `modules/frontend` solves the problem
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/faea1816-0c4f-4849-8952-22bc3940bf77)

**Comment by web-devel** [comment]
@IskandarovRost `^3.0.0-beta.1` is released with the fix

**Comment by IskandarovRost** [comment]
in 3.0.0-beta.1 Frontend module starts without the error/ closed
