### ISSUE TITLE
UUID validation in frontend client is more strict than in Generic UI

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#197]
Generic UI allows UUIDs with non-existent version and variant number. 

UUID format is `xxxxxxxx-xxxx-Mxxx-Nxxx-xxxxxxxxxxxx` where `M` is UUID version and `N` is UUID variant. Valid UUID versions are `[0-5]`, valid variants are `[089ab]`.

However, as @IskandarovRost describes below, in Generic UI it is possible to create a UUID with an invalid version such as `b` and an invalid variant such as `c` (`6ea827b2-d51f-bd58-cbe8-aa68aace6eab`). 

Since fixing it on Generic UI side would be a breaking change, the proposal for now is to relax the validation on frontend side to match the Generic UI.

_Originally posted by @IskandarovRost in the comments to #36:_
> To some entity add UUID propety
> In Vaadin specify the value "6ea827b2-d51f-bd58-cbe8-aa68aace6eab" (or take some ID of some entity)
> Create front module
> Create entity management component for this entity.
> 
> **AR:** Something is wrong with the mask as could not specify such character sequence 
> 
> ![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/490f2499-0056-4c75-89b1-2f1f3bc499d3)

**Comment by IskandarovRost** [comment]
Closed
