### ISSUE TITLE
React Native template

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#20]
### QA Notes

See [this guide](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v3.0.x/client-react-native/starter-guide.html).

**Comment by IskandarovRost** [comment]
gen-cuba-front react-native:app asks opened project two times#230

**Comment by IskandarovRost** [comment]
faced the problem described in #199

**Comment by IskandarovRost** [comment]
Improve react native example component #231
