### ISSUE TITLE
Enforce user to name classes starting from uppercase letter when using CLI

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#201]
1) For some entity create Enttity Management components
2) Specify the classes starting from lower-case letters

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/a6049b30-6659-42b3-a89b-66919f1efb9f)

3) npm run start
**AR:** compillation fails.It seems CLI should not allow such names or just convert them automatically.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/e5d22276-d346-4020-aeef-bd97d70d417e)

**Comment by vadimbasko** [comment]
Cannot reproduce on last version of generator.

**Comment by IskandarovRost** [comment]
Reproduced on 3.0.0
* "dirShift" is defined
* "destination" is defined
* "routing.ts." is rewritten

![image](https://user-images.githubusercontent.com/19840141/81932585-12a09600-95fd-11ea-9fcf-12ef18e02a1e.png)

**AR:** fail to compile
![image](https://user-images.githubusercontent.com/19840141/81932787-5e533f80-95fd-11ea-984f-8b524b7cb7fd.png)

See the attached project. Frontent  is generated in the 'front' directory
[DateTimeSample.zip](https://github.com/cuba-platform/frontend/files/4628187/DateTimeSample.zip)
