### ISSUE TITLE
CRUD component for composite PK entities

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#203]
It seems it is a very rare case to create *composite PK* entity on frontend and manually fill the PK fields, but for generic UI Studio generates the screens with PK fields.
 
1) Create an embeddable entity "KeyEntity"
```
@MetaClass(name = "library_KeyEntity")
@Embeddable
public class KeyEntity extends EmbeddableEntity {
    private static final long serialVersionUID = 7043234715681758024L;

    @Column(name = "KEY_ONE")
    protected String keyOne;

    @Column(name = "KEY_TWO")
    protected Integer keyTwo;

    @Override
    public int hashCode() {
        return Objects.hash(keyTwo, keyOne);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        KeyEntity entity = (KeyEntity) o;
        return Objects.equals(this.keyTwo, entity.keyTwo) &&
                Objects.equals(this.keyOne, entity.keyOne);
    }
...
```
2) Create an entity with embedded PK - select the "KeyEntity" above for the key
```
@Table(name = "LIBRARY_CPK_ENTITY")
@Entity(name = "library_CpkEntity")
public class CpkEntity extends BaseGenericIdEntity<KeyEntity> implements Updatable {
    private static final long serialVersionUID = 6970558227360587278L;

    @EmbeddedId
    protected KeyEntity id;

    @Column(name = "NEEDED_FLD")
    protected String neededFld;
...
```
3) Create Entity management (CRUD) React components 

**AR:** ID properties are not presented neither in List nor in Editor. So could not create a new instance

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/760324e0-593c-4b97-b312-c708db3a9e5f)
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/a4a9161d-9f56-476e-8273-2a56e14c57ca)
**ER:**  In Generic UI the fields of composite PK are presented on edit and browse screens by default
```
...
      <action id="remove" type="remove"/>
            </actions>
            <columns>
                <column id="id.keyOne"/>
                <column id="id.keyTwo"/>
                <column id="neededFld"/>
            </columns>
            <rowsCount/>
...
```

```
...
 <layout expand="editActions" spacing="true">
        <form id="form" dataContainer="cpkEntityDc">
            <column width="250px">
                <textField id="idKeyOneField" property="id.keyOne"/>
                <textField id="idKeyTwoField" property="id.keyTwo"/>
                <textField id="neededFldField" property="neededFld"/>
            </column>
        </form>
...
```

**Comment by vyacheslav-pushkin** [comment]
### Affects

cuba/master
jmix/master

**Comment by web-devel** [comment]
Should be supported on back-end https://github.com/cuba-platform/restapi/issues/49

**Comment by karandashovrz** [comment]
In this ticket was added supporting of some of CRUD operations. If you have entity with composite key you can now:
1) To edit entities. You can edit attributes of entity, but you can't edit attributes of composite keys (they are not displayed).
2) To remove entities.
Operation of adding will not working correct, because attributes of composite keys not displaing in adding screen. This functionality is not implemented yet.
