### ISSUE TITLE
Incorrect Error message when no project model is found

### ISSUE THREAD

**Issue by IskandarovRost** [cuba-platform/frontend#227]
**3.0.0-beta.1**

1) Disable integration in Studio 
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/41952a07-853f-4b54-91d1-bf57b370ab16)
2) launch ``gen-cuba-front react-typescript:app``

As result, the following error appears 

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/7b55615d-490a-45f5-9306-3137ab7bdd1f)

3) Export the project model: launch CUBA->Advanced->Export Project Model in Studio

4) launch `` gen-cuba-front react-typescript:app --projectModel ../../projectModel.json ``

**AR:** Unknown option '--projectModel'. Probably it was renamed.
![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/67495949-bebe-4a31-9531-629334dc94e1)

**Comment by web-devel** [comment]
I vote to revert full option name to `--projectModel`

**Comment by IskandarovRost** [comment]
the error text is changed to --model
