### ISSUE TITLE
error when generating sdk:all

### ISSUE THREAD

**Issue by BryanYin** [cuba-platform/frontend#261]
configured IDEA with this:
![image](https://user-images.githubusercontent.com/25950822/84972455-7add1d00-b151-11ea-897c-a81b11ff3118.png)

Then try to generate sdk for models and api:

```
 ~/path/to/cuba/project/frontend   master ✚  npm install -g @cuba-platform/front-generator@3.0.0-beta.3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/gen-cuba-front -> /usr/local/lib/node_modules/@cuba-platform/front-generator/bin/gen-cuba-front.js
+ @cuba-platform/front-generator@3.0.0-beta.3
updated 1 package in 61.465s
  ~/path/to/cuba/project/frontend   master ✚  gen-cuba-front sdk:all
? Please select CUBA project you want to use for generation szdata [/cuba/project/name]
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: Specified model file does not exist undefined
    at SdkAllGenerator._readProjectModel (/usr/local/lib/node_modules/@cuba-platform/front-generator/lib/common/base-generator.js:77:19)
    at SdkAllGenerator.<anonymous> (/usr/local/lib/node_modules/@cuba-platform/front-generator/lib/generators/sdk/sdk-generator.js:66:46)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@cuba-platform/front-generator/lib/generators/sdk/sdk-generator.js:5:58)
Emitted 'error' event on SdkAllGenerator instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/@cuba-platform/front-generator/node_modules/yeoman-generator/lib/index.js:924:20)
```

**Comment by vyacheslav-pushkin** [comment]
Hi @BryanYin,

I wasn't able to reproduce it. Which Studio version do you use? Are you able to reproduce it with [this project](https://github.com/cuba-platform/frontend/tree/master/sample-car-rent)? If not, could you please post your project somewhere?

**Comment by BryanYin** [comment]
Hi @vyacheslav-pushkin 

Yes, it's reproduced the same on my mac with the `sample-car-rent project`.

I'm using cuba studio version:
CUBA Studio plugin version: 13.2-191
IntelliJ version: IntelliJ IDEA 2020.1 (Ultimate Edition)

Node.js version:
node -v
v13.8.0

Checking the compiled js code, it seems the code can't work in any case, please suggest:
![image](https://user-images.githubusercontent.com/25950822/85144614-ff2cbe80-b27d-11ea-8054-0c7e3b64f69b.png)

**Comment by BryanYin** [comment]
Hi @vyacheslav-pushkin, 

I installed `@cuba-platform/front-generator@3.0.1` and it works now, thanks!
