### ISSUE TITLE
Сorrect a typo. Docs front / React Client / Routing and Menu.

### ISSUE THREAD

**Issue by HegelPro** [cuba-platform/frontend#353]
Rename the menuLink field value from /pest to /pets
[picture](https://gyazo.com/46321cda0a860dc7bd2b7c138421eb16?token=9703a257ff1099c829798e14beaf17f6)
[docs link](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v20.1/client-react/routing.html)

##### Affected branches:

- jmix/master
- cuba/master
- cuba/release_20.1

**Comment by aditya28sarin** [comment]
Can you assign me this issue?

**Comment by vyacheslav-pushkin** [comment]
Hi @aditya28sarin,

Looks like the fix has already been committed by @karandashovrz.

Hi @karandashovrz,

Could you please open a PR? Also, please don't use `ISSUES CLOSED` as it will automatically close the issue upon merge, thus skipping QA step.
