### ISSUE TITLE
Support all possible entity property types

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#36]
- ✅ Add support for remaining temporal fields: 
```
localDate, localTime, localDateTime, offsetDateTime, offsetTime
```
- ✅ Render `InputNumber` for numeric fields:
```
long, decimal, int, double
```
> Support for big numbers is tracked under separate ticket cuba-platform/frontend#99 as it depends on REST API changes

- ✅ Add support for masked fields. Render masked field for  `uuid`.
- ✅ Fix displaying of Associations:
  - Values of many-to-many Associations are not displayed in DataTable
  - Associations should be shown in the same manner as in the Generic UI:
     - One-to-many Associations are not shown anymore at the owning side
     - One-to-one Associations are not shown anymore at the inverse side
- ✅ Do not display `byteArray` (similar to Generic UI)
- ✅ Support `long`, `uuid` and all temporal types in DataTable's custom filters

**Comment by IskandarovRost** [comment]
**QA:**
1) Check BigDecimal value of different formats, separators, presigion, scale (https://doc.cuba-platform.com/manual-7.2/entity_attr_annotations.html#numberFormat_annotation)
2) Display ID of UUID entity. is there a difference between ID and UUID datatype
3) Double property. make some bizare NumberFormat 
4) Make an integerFld mandatory specify some custom validation message

**Comment by IskandarovRost** [comment]
To some entity add UUID propety
In Vaadin specify the value "6ea827b2-d51f-bd58-cbe8-aa68aace6eab" (or take some ID of some entity)
Create front module
Create entity management component for this entity.

**AR:** Something is wrong with the mask as could not specify such character sequence 

![image.png](https://images.zenhubusercontent.com/5aec53f14b5806bc2bd1c28a/490f2499-0056-4c75-89b1-2f1f3bc499d3)

**Comment by IskandarovRost** [comment]
See also #141 about embedded attributes

**Comment by vyacheslav-pushkin** [comment]
@IskandarovRost 

> Reopen
> AR: Something is wrong with the mask as could not specify such character sequence

This ticket is quite a large feature, so it's best if we track such bugs as separate tickets. Could you pls open one and assign it to me? Thanks.

**Comment by vyacheslav-pushkin** [comment]
Opened #197, moving this ticket back to QA.

**Comment by IskandarovRost** [comment]
Text fields are the same for String proerties with the different length/
Created enhancement  #217

**Comment by IskandarovRost** [comment]
closed
