### ISSUE TITLE
Change error message for new entity creation in case lost connection

### ISSUE THREAD

**Issue by maistrenkoIulia** [cuba-platform/frontend#362]
v. 4.0.0-beta.1

TC: run app>open front
set network>offline
open entity management>create>input values>submit
ER: informative error should be displayed
AR:  'Error'
![image](https://user-images.githubusercontent.com/66992566/105360091-a48f8280-5c11-11eb-85eb-4770c258179b.png)

**Comment by vyacheslav-pushkin** [comment]
### Affects:

cuba/master
jmix/master
