### ISSUE TITLE
Composite key is not supported by DataTable

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [cuba-platform/frontend#367]
https://www.cuba-platform.com/discuss/t/react-datatable-with-composite-key/14588

- `selectedRowKey` returned as Object
- rows will have the same key `[object Object]`

### Affects

cuba/master
jmix/master

**Comment by karandashovrz** [comment]
In this ticket was added supporting of composite keys in data table. If you have entity with composite key, you will not receive anymore errors and warnings in console after DataTable rendering and selecting rows.
