### ISSUE TITLE
Field for composition attribute does not show in editor screen

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/frontend#374]
### Environment

Custom front generator version: v. 4.0.0-beta.1

### Description of the bug or enhancement

1. Create a new project 
2. Create the first entity 
3. Create the second entity with composition attribute
4. Create a new view for the second entity
5. Create a new entity management frontend component
6. Run the project and open the created component for edition

AR: Field for composition attribute does not exist.
![изображение](https://user-images.githubusercontent.com/24281695/107026805-b2720580-67c4-11eb-9590-9634a92736e5.png)

**Comment by karandashovrz** [comment]
This bug is problem in stuidio. Fix of this issue will be after implementation https://youtrack.haulmont.com/issue/STUDIO-9160
