### ISSUE TITLE
React hooks support

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/frontend#4]
* update mobX
* design data componts hooks

## QA Notes

It is adviced to fully test the entity editor created with `react-typescript:entity-management-hooks`.

**Comment by vadimbasko** [comment]
cuba-react-core Collection contains methods for functional components that not used now and not covered by tests. We need to rework them and add test or remove after hooks will be implemented.
```
withDataCollection
DataCollectionInjected
DataCollectionStore#properties()
```

**Comment by IskandarovRost** [comment]
QA. Check:

1. How to create and delete the component
2. How it is added to menu (routing.ts)
3. Different ID types: UUID, Integer, Long, +identity
4. “ID Assigned by user” in JMIX
5. DTO entity in JMIX
6. String ID entity 
7. Composite PK entity
8. Reference entity: different field types
9. Dates and times: local dates etc
10. Main-details Composition
11. Hierarchy (“Document”-”Parent document”)
12. Studio support: create frontend with the version  where the feature has not been supported yet
13. Filtering and sorting in the table component

**Comment by IskandarovRost** [comment]
closed
