### ISSUE TITLE
[FileUploadComponent] AdBlock brakes file preview functionality

### ISSUE THREAD

**Issue by glebfox** [cuba-platform/frontend#87]
[rest-image.zip](https://github.com/cuba-platform/frontend/files/4127797/rest-image.zip)

![Jan-29-2020 16-14-26](https://user-images.githubusercontent.com/6077149/73355840-73a49800-42b2-11ea-9486-c327f684e081.gif)

Pay attention that Safari has built-in ad-blocking functionality.

### QA Notes

Now instead of opening an image in a new tab, we will use [ImagePreview](https://doc.cuba-platform.com/frontend/cuba-frontend-docs/v3.0.x/cuba-react-ui/file-upload.html) component.

**Comment by IskandarovRost** [comment]
verified
